# Generated by Django 4.2.7 on 2023-12-04 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OffenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=15)),
                ('offense_type', models.CharField(max_length=300)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lrn', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_number', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('selected_offense', models.CharField(choices=[('Offense1', 'Constant loitering in the school perimeters'), ('Offense2', 'Vandalism and deliberately causing damage to school properties'), ('Offense3', 'Constant used of unauthorized electrical outlets for personal used'), ('Offense4', 'Constant used of cellphones during classes hours'), ('Offense5', 'Constant misbehaving activities that cause disruption'), ('Offense6', 'Bullying'), ('Offense7', 'Threats'), ('Offense8', 'Physical injury'), ('Offense9', 'Cheating'), ('Offense10', 'Falsifying school and teachers documents'), ('Offense11', 'Constant absences'), ('Offense12', 'Cutting of classes'), ('Offense13', 'Falsifying school and teachers documents'), ('Offense14', 'Fighting on campus and off campus'), ('Offense15', 'Position of deadly weapon'), ('Offense16', 'Smoking inside the campus'), ('Offense17', 'Drug Related issues'), ('Offense18', 'Gambling'), ('Offense19', 'Stealing'), ('Offense20', 'Position/ drinking of alcoholic beverages'), ('Offense21', 'Sexual harassments'), ('Others', 'Others')], default='Offense1', max_length=300)),
                ('custom_description', models.CharField(blank=True, max_length=300, null=True)),
                ('narrative_report', models.CharField(max_length=300)),
                ('school_year', models.CharField(choices=[('2022-2023', 'SY2022-2023'), ('2023-2024', 'SY2023-2024'), ('2024-2025', 'SY2024-2025'), ('2025-2026', 'SY2025-2026'), ('2026-2027', 'SY2026-2027'), ('2027-2028', 'SY2027-2028')], default='2023-2024', max_length=15)),
                ('pictures', models.ImageField(blank=True, null=True, upload_to='violations')),
                ('date_committed', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('intervention_date', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(choices=[('Meeting with the adviser', 'Meeting with the adviser'), ('Call the attention of parents', 'Call the attention of parents'), ('Give extracurricular activities', 'Give extracurricular activities'), ('Endorse to Child Protection Office', 'Endorse to Child Protection Office'), ('Endorse to Brgy. Child Protection Council', 'Endorse to Brgy. Child Protection Council'), ('Reprimand', 'Reprimand')], default='Meeting with the adviser', max_length=100)),
                ('recommendation', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinetracking.student')),
            ],
        ),
    ]
