# Generated by Django 4.2.7 on 2023-11-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinetracking', '0003_student_date_posted_violation_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='school_year',
            field=models.CharField(choices=[('2019', 'SY2019-2020'), ('2020', 'SY2020-2021'), ('2021', 'SY2021-2022'), ('2022', 'SY2022-2023'), ('2023', 'SY2023-2024')], default='2023', max_length=100),
        ),
    ]
