# Generated by Django 4.2.7 on 2023-11-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinetracking', '0004_violation_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='pictures',
            field=models.ImageField(upload_to='violations/'),
        ),
    ]
